import type { Product } from "@/types/inventory";

export const seedProducts: Product[] = [
  {
    id: "sku-aashirvaad-atta",
    sku: "ATTA-10K",
    name: "Aashirvaad Shudh Chakki Atta 10kg",
    category: "Grocery staples",
    stock: 164,
    threshold: 210,
    reorderQuantity: 1400,
    unitCost: 382,
    salesVelocityPerHour: 10.7,
    lastFourDayDropPct: 84,
    supplier: "Delhi NCR FMCG Depot",
    updatedAt: new Date().toISOString()
  },
  {
    id: "sku-bajaj-room-heater",
    sku: "HTR-BJ2K",
    name: "Bajaj Majesty 2000W Room Heater",
    category: "Winter appliances",
    stock: 57,
    threshold: 95,
    reorderQuantity: 520,
    unitCost: 2199,
    salesVelocityPerHour: 2.7,
    lastFourDayDropPct: 89,
    supplier: "Karol Bagh Appliance Traders",
    updatedAt: new Date().toISOString()
  },
  {
    id: "sku-boatlifestyle-earbuds",
    sku: "BUD-AIRD",
    name: "boAt Airdopes 141 Bluetooth Earbuds",
    category: "Mobile accessories",
    stock: 121,
    threshold: 150,
    reorderQuantity: 900,
    unitCost: 1099,
    salesVelocityPerHour: 7.5,
    lastFourDayDropPct: 78,
    supplier: "Gurugram Electronics Hub",
    updatedAt: new Date().toISOString()
  },
  {
    id: "sku-basmati-rice",
    sku: "RICE-DB5",
    name: "Daawat Rozana Super Basmati Rice 5kg",
    category: "Grocery staples",
    stock: 288,
    threshold: 140,
    reorderQuantity: 850,
    unitCost: 512,
    salesVelocityPerHour: 3.3,
    lastFourDayDropPct: 34,
    supplier: "Karnal Grain Exchange",
    updatedAt: new Date().toISOString()
  },
  {
    id: "sku-women-kurta-set",
    sku: "KURT-WF",
    name: "Women Printed Cotton Kurta Set",
    category: "Ethnic fashion",
    stock: 73,
    threshold: 130,
    reorderQuantity: 640,
    unitCost: 799,
    salesVelocityPerHour: 3.9,
    lastFourDayDropPct: 86,
    supplier: "Jaipur Textile Market",
    updatedAt: new Date().toISOString()
  },
  {
    id: "sku-pressure-cooker",
    sku: "COOK-5L",
    name: "Prestige Popular Aluminium Pressure Cooker 5L",
    category: "Kitchen essentials",
    stock: 246,
    threshold: 110,
    reorderQuantity: 420,
    unitCost: 1249,
    salesVelocityPerHour: 1.8,
    lastFourDayDropPct: 26,
    supplier: "Noida Homeware Distributors",
    updatedAt: new Date().toISOString()
  },
  {
    id: "sku-himalaya-facewash",
    sku: "SKIN-HFW",
    name: "Himalaya Purifying Neem Face Wash 200ml",
    category: "Beauty and personal care",
    stock: 412,
    threshold: 180,
    reorderQuantity: 900,
    unitCost: 176,
    salesVelocityPerHour: 4.4,
    lastFourDayDropPct: 31,
    supplier: "Ghaziabad Wellness Supply",
    updatedAt: new Date().toISOString()
  }
];
